### ISSUE TITLE
About the Negative link in the paper

### ISSUE THREAD

**Issue by sdsy888** [dengdan/seglink#10]
Hi, I'm checking your code and thank you for your code.
But I didn't found the `negtive link` which was mentioned in the paper. Does [the code](https://github.com/dengdan/seglink/blob/master/tf_extended/seglink.py) has not implemented this part?
Thank you.

**Comment by dengdan** [comment]
Negative links are selected use OHNM, in [loss calculation](https://github.com/dengdan/seglink/blob/master/nets/seglink_symbol.py#L247)

**Comment by sdsy888** [comment]
Thank you!
Sorry for ignoring the implementation.
