### ISSUE TITLE
Two titan xp of 12GB can only handle 512*512 and batch size=8 on my machine....

### ISSUE THREAD

**Issue by JarveeLee** [dengdan/seglink#12]

**Comment by JarveeLee** [comment]
When set to batch size = 16 it report out of memory...possible solution?

**Comment by dengdan** [comment]
Could show me the command for training? I guess you had got confused with `BATCH_SIZE` and `BATCH_SIZE_PER_GPU`.

**Comment by JarveeLee** [comment]
@dengdan Ah you are right 8 means size per gpu......
tf.app.flags.DEFINE_integer('batch_size', 8, 'The number of samples in each batch.')

**Comment by JarveeLee** [comment]
this is my setting 
tf.app.flags.DEFINE_integer('batch_size', 8, 'The number of samples in each batch.')
tf.app.flags.DEFINE_integer('num_gpus', 2, 'The number of gpus can be used.')
@dengdan

**Comment by dengdan** [comment]
No. Not this configuration, because they are only default params. I mean your command for training, like:
```
python train_seglink.py --batch_size=....
```

**Comment by JarveeLee** [comment]
python train_seglink.py --batch_size=16 

![image](https://user-images.githubusercontent.com/21051247/30256995-5d74694a-96e1-11e7-822c-006dcfd56439.png)
@dengdan

**Comment by dengdan** [comment]
Where is your COMMAND?

**Comment by dengdan** [comment]
OK. Could you paste the content of the training_config.txt here?

**Comment by JarveeLee** [comment]
![image](https://user-images.githubusercontent.com/21051247/30257131-6e58e51e-96e2-11e7-8002-f8ba3384328f.png)

**Comment by dengdan** [comment]
What's the value of  `config.batch_size_per_gpu` ?

**Comment by JarveeLee** [comment]
It is 8

'batch_size=16'
'batch_size_per_gpu=8'
'link_cls_loss_weight=1.0'
'__name__=config'
'anchor_scale_gamma=1.5'
'data_format=NHWC'
"clone_scopes=['clone_0', 'clone_1']"
'num_anchors=5460'
'seg_conf_threshold=0.5'

**Comment by dengdan** [comment]
Well, I tried again on my own machine, and it's OK to put 8 images per gpu when image_size=512.

**Comment by dengdan** [comment]
Execute `nvidia-smi` and show the result here before training.

**Comment by dengdan** [comment]
And your tensorflow version?

**Comment by JarveeLee** [comment]
tf 1.1.0 and py2.7

**Comment by dengdan** [comment]
Everything seems to be OK. Actually, when I am using batch_size_per_gpu=8, the memory is nearly not enough, because the warnings like this appear:
![default](https://user-images.githubusercontent.com/4814582/30257584-cecab8f2-96e5-11e7-809c-eae07df07885.png)
Some tiny unkown differences may result in a little higher requirement of GPU memory. So I can only suggest you try a smaller batch size like 14, and batch_size_per_gpu = 7.

**Comment by dengdan** [comment]
Have you configured num_gpus in `python train_seglink.py --batch_size=16`? If not, add it:
```
python train_seglink.py --batch_size=16 --num_gpus=2
```

**Comment by JarveeLee** [comment]
Alright I'll try to optimize model within my hardware's capability.......Thanks for your online debug help haha
