### ISSUE TITLE
Trained Model Links not working

### ISSUE THREAD

**Issue by ldrabeck** [dengdan/seglink#16]
It seems that the links for the trained models seglink-384 and seglink-512 are not longer active.  Could someone please update these to working links.  Thanks

**Comment by dengdan** [comment]
I've checked the links just now, and they are still OK.

**Comment by ldrabeck** [comment]
Thanks for the confirmation of the link being ok.  I had to go outside the company firewall and then I was able to get the trained models.  Thanks.  You can close this open issue.
