### ISSUE TITLE
poor performance using seglink-384

### ISSUE THREAD

**Issue by zw88** [dengdan/seglink#17]
I have tested ICDAR2013 with seglink-384 model and visualized the result images. The seg_conf is set 0.8 and link_conf 0.5. However the performance was very poor. Can you help explain the reason?

**Comment by dengdan** [comment]
Two measures should help:
1. Fine tune the model on IC13-train
2. Find proper thresholds for IC13-test via grid search, for the 0.8 and 0.5 are thresholds selected for IC15-train.
