### ISSUE TITLE
About bboxes_filter_overlap

### ISSUE THREAD

**Issue by abc8350712** [dengdan/seglink#21]
I read the code and something make me confused.
In the process of data augmentation,the following function appears.

bboxes_filter_overlap(labels, bboxes,xs, ys, threshold, scope=None, assign_negative = False)

Is the value in bboxes of parameters may be negative?

I am looking forward to your help！

**Comment by dengdan** [comment]
The label value of a bbox might be negative after preprocessing, meaning do-not-care. Such bboxes are ignored and won't contribute the loss when training.

**Comment by abc8350712** [comment]
The function is
`def bboxes_filter_overlap(labels, bboxes,xs, ys, threshold, scope=None, assign_negative = False):
    """Filter out bounding boxes based on (relative )overlap with reference
    box [0, 0, 1, 1].  Remove completely bounding boxes, or assign negative
    labels to the one outside (useful for latter processing...).

    Return:
      labels, bboxes: Filtered (or newly assigned) elements.
    """
    with tf.name_scope(scope, 'bboxes_filter', [labels, bboxes]):
        scores = bboxes_intersection(tf.constant([0, 0, 1, 1], bboxes.dtype),bboxes)
                    
        mask = scores > threshold
        if assign_negative:
            labels = tf.where(mask, labels, -labels)
        else:
            labels = tf.boolean_mask(labels, mask)
            bboxes = tf.boolean_mask(bboxes, mask)
            scores = bboxes_intersection(tf.constant([0, 0, 1, 1], bboxes.dtype),bboxes)
            xs = tf.boolean_mask(xs, mask);
            ys = tf.boolean_mask(ys, mask);
        return labels, bboxes, xs, ys`

**Comment by dengdan** [comment]
In preprocessing and data augmentation, the original images are randomly cropped, and the coordinate values of a bounding box might be negative, and then the scores in method `bboxes_intersection` may be less than 1.0.
