### ISSUE TITLE
About transofrom_cv_rect

### ISSUE THREAD

**Issue by abc8350712** [dengdan/seglink#23]
When a rectangle is rotated to horizontal direction, should width-side be horizontal?
should the length of width-side be larger than than the length of height-side?

The input parameter rects is generated by minarearect function of opncv
<pre><code>
def transform_cv_rect(rects):
    only_one = False
    if len(np.shape(rects)) == 1:
        rects = np.expand_dims(rects, axis = 0)
        only_one = True
    assert np.shape(rects)[1] == 5, 'The shape of rects must be (N, 5), but meet %s'%(str(np.shape(rects)))
    rects = np.asarray(rects, dtype = np.float32).copy()
    num_rects = np.shape(rects)[0]
    for idx in xrange(num_rects):
        cx, cy, w, h, theta = rects[idx, ...];
        #assert theta < 0 and theta >= -90, "invalid theta: %f"%(theta) 
        if abs(theta) > 45 or (abs(theta) == 45 and w < h):
            w, h = [h, w]
            theta = 90 + theta
        rects[idx, ...] = [cx, cy, w, h, theta]
    if only_one:
        return rects[0, ...]
    return rects 
</code>
</pre>
After using the above function, it seems that it can't promise that the length of width is larger than the length of height.

I'm so confused.

**Comment by dengdan** [comment]
Yes, the width does not have to be larger than the height.
I made a note on how the transformation is going on: http://fromwiz.com/share/s/34GeEW1RFx7x2iIM0z1ZXVvc2yLl5t2fTkEg2ZVhJR2n50xg

**Comment by abc8350712** [comment]
Thansk a lot.But if the rotated rectangle whose width-side is smaller than length-side,and the width-side is horizontal.(thin shape).

In this situaltion,How can it be cropped?

**Comment by dengdan** [comment]
This situation is not that special, and can be well dealt with via the groundtruth calculation algorithm described in the paper.

**Comment by abc8350712** [comment]
The method used to  solve the situtation(thin shape) is as followed.
The bbox may be in thin shape.
<pre><code>
def crop_horizontal_bbox_using_anchor(bbox, anchor):
    """Step 3 in Figure 5 in seglink paper
    The crop operation is operated only on the x direction.
    Args:
        bbox: a horizontal bbox with shape = (5, ) or (4, ). 
    """
    assert np.shape(anchor) == (4, ), "anchor must be a vector of length 4"
    assert np.shape(bbox) == (5, ) or np.shape(bbox) == (4, ), "bbox must be a vector of length 4 or 5"
    
    # xmin and xmax of the anchor    
    acx, acy, aw, ah = anchor
    axmin = acx - aw / 2.0;
    axmax = acx + aw / 2.0;
    
    # xmin and xmax of the bbox
    cx, cy, w, h = bbox[0:4]
    xmin = cx - w / 2.0
    xmax = cx + w / 2.0
    
    # clip operation
    xmin = max(xmin, axmin)
    xmax = min(xmax, axmax)
    
    # transform xmin, xmax to cx and w
    cx = (xmin + xmax) / 2.0;
    w = xmax - xmin
    bbox = bbox.copy()
    bbox[0:4] = [cx, cy, w, h]
    return bbox
</pre?</code>

won't the height of returned bbox be much larger than the height of default box?

**Comment by dengdan** [comment]
No, the height ratio between a ground truth bounding box and its matched anchors must be within 1.5

**Comment by abc8350712** [comment]
Since the width does not have to be larger than the height, so when the input rect is in thin shape whose height may be more larger than width.

I know  that anchor_rect_height_ratio(anchor, rect) function is used to make sure that the width ratio between rect and anchor in certain range.
<pre><code>
def anchor_rect_height_ratio(anchor, rect):
    """calculate the height ratio between anchor and rect
    """
    rect_height = min(rect[2], rect[3])
    anchor_height = anchor[2] * 1.0
    ratio = anchor_height / rect_height
    return max(ratio, 1.0 / ratio)
</code></pre>

The rect_height is the smaller size of rect,which can be height, but can also be width.
So i think the height of returned bbox may be much larger than the height of default box.
Am i wrong?

Thanks a lot.

**Comment by dengdan** [comment]
No, you are right. I have made a mistake here, the code: 
```
rect_height = min(rect[2], rect[3])
``` 
in https://github.com/dengdan/seglink/blob/master/tf_extended/seglink.py#L15 should be:
```
rect_height = rect[3]
```

This mistake is supposed to have made more anchors matched to long vertical text boxes. However, its influence is not significant when only very few vertical boxes exist, as the case in IC15.  You can fix it right, get new models trained and make a pull request if you are interested in it and convenient. Or I will fix it myself when I got time.

Thanks a lot for your correction.

**Comment by abc8350712** [comment]
Thank you!
