### ISSUE TITLE
The f-measure of evaluation

### ISSUE THREAD

**Issue by abc8350712** [dengdan/seglink#24]
I used the command
<pre><code>
python eval_seglink.py --checkpoint_path=./seglink/model.ckpt-136750  --dataset_name=icdar2015 --dataset_split_name=test --dataset_dir=./tf_records
</code></pre>
to evaluate the model provided by you(seglink-384 model)

I change 'seg_conf_threshold' and 'link_conf_threshold' to 0.8 and 0.5 separately.

when i set the test image as 384x384, the result is
Recall, Precision, Fmean = [0.48117587][0.72381693][0.57806695]

when I set the test image as 512x512, the result is
Recall, Precision, Fmean = [0.61840743][0.78477693][0.69172925]

It doesn't match the result you provided.
Is there anything i miss?

**Comment by BowieHsu** [comment]
if you want to test ICDAR results, the images size should be 1280 * 720 @abc8350712

**Comment by abc8350712** [comment]
Thank You!!@BowieHsu
