### ISSUE TITLE
ImportError: No module named util

### ISSUE THREAD

**Issue by shengzhang90** [dengdan/seglink#27]
ImportError: No module named util

**Comment by idefix92** [comment]
did you connect pylib/src to your PYTHONPATH?

**Comment by dheeru999** [comment]
i have connected pylib/src to my PYTHONPATH ..   but still i'am facing the same issue

**Comment by whyccny** [comment]
@idefix92 Could you please tell me how do I connect pylib/src to my PYTHONPATH?
