### ISSUE TITLE
Export for serving from TFS

### ISSUE THREAD

**Issue by abuvaneswari** [dengdan/seglink#31]
Hello,

Great job with the seglink model code as well as with making the checkpoint available! 

I would like to save a seglink checkpoint as a graph (e.g saved_model.pb) for serving from TFS -
 https://www.tensorflow.org/serving/ 

TFS requires that there be no py_func usage (so, whatever numpy operations you carryout in the function, convert it to tf operations) - see this reference link: https://github.com/tensorflow/serving/issues/495

My questions / requests to you at this point:
1) Do you plan to implement an export graph function, similar to the inception saved model function in the TFS example ( https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_saved_model.py ) ?
2) If not, is it possible for you to convert your numpy ops to pure tf ops in the functions that are called from tf.py_func() in tf_extended/seglink..py, and make it available as another fork?

Thank you very much,
Regards,
Buvana

**Comment by dengdan** [comment]
Thanks for your attention. I'm sorry that I won't have enough time to re-implement them with pure tf ops. You are welcome to finish it if you are convenient.
