### ISSUE TITLE
UnboundLocalError: local variable 'setproctitle' referenced before assignment

### ISSUE THREAD

**Issue by JohnWnx** [dengdan/seglink#41]
Hi, I have the dependencies installed for seglink already.

However, when I tried to run the program, I have encountered such problem:

![image](https://user-images.githubusercontent.com/40804580/43889371-8f434a2a-9bf6-11e8-8493-f431b353549a.png)

Could anyone advise how can I solve this?

Thanks!

**Comment by jiayi-wei** [comment]
Have you solve this problem?

**Comment by northeastsquare** [comment]
pip install ...

**Comment by jamesbondzhou** [comment]
Have you solve this problem?
