### ISSUE TITLE
using_moving_average not found

### ISSUE THREAD

**Issue by LearnerInGithub** [dengdan/seglink#8]
@dengdan  When I set using_moving_average=1,  the program report error:
NotFoundError (see above for traceback): Key vgg/conv5/conv5_2/weights/ExponentialMovingAverage not found in checkpoint.  How to use this feature in this repo?

**Comment by dengdan** [comment]
When I was training the models uploaded, I didn't use MovingAverage. If you wanna use it, you may have to  train a model by yourself.
